
"""crear tabla comments

Revision ID: 8668140716c8
Revises: 060d8d12af40
Create Date: 2026-06-02 12:59:54.499019

"""
from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8668140716c8'
down_revision: Union[str, Sequence[str], None] = '060d8d12af40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
